# Generated by Django 4.2 on 2024-06-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_star_product_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
