# Generated by Django 4.2 on 2024-06-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_star_delete_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.attributegroup'),
            preserve_default=False,
        ),
    ]
